/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#482900',
        'error': '#ffb4ab',
        'inverse-primary': '#6d3bd7',
        'surface': '#131315',
        'on-primary': '#ffffff',
        'tertiary': '#ffb869',
        'surface-container-low': '#1b1b1d',
        'on-tertiary-fixed-variant': '#673d00',
        'on-tertiary-container': '#3f2300',
        'primary-container': '#2d1b4d',
        'on-error-container': '#ffdad6',
        'surface-container-lowest': '#0e0e10',
        'primary-fixed': '#e9ddff',
        'surface-container-highest': '#353437',
        'surface-variant': '#353437',
        'surface-tint': '#8b5cf6',
        'error-container': '#93000a',
        'outline-variant': '#494454',
        'secondary-fixed': '#e4e2e4',
        'on-secondary-fixed-variant': '#474649',
        'on-error': '#690005',
        'on-primary-container': '#e9ddff',
        'primary': '#8b5cf6',
        'tertiary-fixed': '#ffdcbb',
        'on-surface-variant': '#cbc3d7',
        'surface-container': '#201f21',
        'surface-container-high': '#2a2a2c',
        'tertiary-fixed-dim': '#ffb869',
        'on-secondary-fixed': '#1b1b1d',
        'outline': '#958ea0',
        'surface-dim': '#131315',
        'secondary-fixed-dim': '#c8c6c8',
        'on-surface': '#e5e1e4',
        'inverse-surface': '#e5e1e4',
        'background': '#131315',
        'inverse-on-surface': '#303032',
        'on-secondary-container': '#b6b4b7',
        'on-primary-fixed': '#23005c',
        'on-tertiary-fixed': '#2c1700',
        'on-primary-fixed-variant': '#5516be',
        'secondary': '#c8c6c8',
        'tertiary-container': '#ca801e',
        'secondary-container': '#474649',
        'surface-bright': '#39393b',
        'primary-fixed-dim': '#d0bcff',
        'on-secondary': '#303032',
        'on-background': '#e5e1e4',
        'border': '#494454',
        'border-light': '#494454',

        'status-success': '#16a34a',
        'status-warning': '#ea580c',
        'status-danger': '#dc2626',
        'status-info': '#2563eb',

        'rank-s': '#fbbf24',
        'rank-a': '#9ca3af',
        'rank-b': '#d97706',
        'rank-c': '#dc2626',
        'rank-d': '#6b7280',

        workspace: {
          bg: '#1a1a2e',
          surface: '#232340',
          'canvas-bg': '#12121f',
          text: '#e8e8f0',
          'text-secondary': '#9494b8',
          accent: '#4fc3f7',
          border: '#2a2a4a',
        },
      },
      fontFamily: {
        geist: ['Geist', 'sans-serif'],
        sans: ['Geist', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'container-padding': '24px',
        'panel-gap': '20px',
        'base': '8px',
        'gutter': '16px',
      },
      borderRadius: {
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      keyframes: {
        fadeIn: {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out forwards',
      },
    },
  },
  plugins: [],
}
